### ISSUE TITLE
:bug: Device child not containing id

### ISSUE THREAD

**Issue by poowqnp** [MateoGreil/homeassistant-comwatt#10]
Hello, I had this add on running and working perfectly (thank you btw!) but as of 01/01/2024, there is no entities showing up anymore. I tried reinstalling both HACS and the comwatt add-on without success. Coincidentally, I called up the Comwatt SAV because my G4 box had problems connecting to the cloud for a couple of days after 01/01/2024 and the Comwatt SAV monsieur said that they had been doing some MAJs. So Just wanted to check if I am the only one currently having issues or if it is a general thing? Cheers guys keep up the good work!

**Comment by MateoGreil** [comment]
Hello,

Just to be sure to understand :
This integration is not working in HomeAssistant, but you can go to `energy.comwatt.com` and all is working ?

Personnally all is still working.

Can you maybe send me your logs (with a search `comwatt`) ?

**Comment by poowqnp** [comment]
yes that is correct. 
 the comwatt devices in home assistant stopped responding. Adding the comwatt integration again gives 0 devices & enteties. but their interface at energy.comwatt.com is still working, even though it did have 4 days of downtime for me. I've tripplechecked passwords of course. 
 
Errorlogs reads as following:
 
 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up comwatt platform for sensor
File "/config/custom_components/comwatt/sensor.py", line 33, in async_setup_entry
new_devices.append(ComwattPowerSensor(client, entry.data["username"], entry.data["password"], child))
File "/config/custom_components/comwatt/sensor.py", line 94, in __init__

**Comment by MateoGreil** [comment]
Did you add any device to your comwatt setup at the moment of the bug ?

**Comment by poowqnp** [comment]
no, this just happened out of the blue, and then repeats if I try to remove and re-install the comwatt entity.

**Comment by MateoGreil** [comment]
I think that's cause of the number of requests, and number of clients.
This should be fixed by https://github.com/MateoGreil/homeassistant-comwatt/issues/4

**Comment by MateoGreil** [comment]
Hello, I think it could be better now I think https://github.com/MateoGreil/homeassistant-comwatt/issues/4 is fixed.
Can you try ?

**Comment by poowqnp** [comment]
Hello. Terribly sorry but my errors persists. 
I managed to solve it once by removing the integration and removing hacs, then rebooting and reinstalling everything. But it only worked for a couple of days. Now I'm stuck with the same result.

Here is an extrait of the error log while trying to add the comwatt integration:


2024-02-28 10:57:44.508 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 51, in get
    return await WebSocketHandler(request.app["hass"], request).async_handle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/http.py", line 284, in async_handle
    await wsock.prepare(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_ws.py", line 152, in prepare
    payload_writer = await super().prepare(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 415, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 423, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_response.py", line 503, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/http_writer.py", line 130, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2024-02-28 10:57:47.802 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up comwatt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/comwatt/sensor.py", line 32, in async_setup_entry
    new_devices.append(ComwattPowerSensor(hass, entry, child))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comwatt/sensor.py", line 108, in __init__
    self._attr_unique_id = f"{self._device['id']}_power"
                              ~~~~~~~~~~~~^^^^^^
KeyError: 'id'
2024-02-28 10:59:24.916 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up comwatt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/comwatt/sensor.py", line 32, in async_setup_entry
    new_devices.append(ComwattPowerSensor(hass, entry, child))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comwatt/sensor.py", line 108, in __init__
    self._attr_unique_id = f"{self._device['id']}_power"
                              ~~~~~~~~~~~~^^^^^^
KeyError: 'id'
2024-02-28 11:00:08.420 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry ikea@dataairlines.net for comwatt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 605, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comwatt/__init__.py", line 31, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
KeyError: '(removed this part)'
2024-02-28 11:00:12.120 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry ikea@dataairlines.net for comwatt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 605, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comwatt/__init__.py", line 31, in async_unload_entry
    hass.data[DOMAIN].pop(entry.entry_id)
KeyError: '(removed this part)'
2024-02-28 11:00:48.330 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up comwatt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/comwatt/sensor.py", line 32, in async_setup_entry
    new_devices.append(ComwattPowerSensor(hass, entry, child))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comwatt/sensor.py", line 108, in __init__
    self._attr_unique_id = f"{self._device['id']}_power"
                              ~~~~~~~~~~~~^^^^^^
KeyError: 'id'
2024-02-28 11:01:06.503 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up comwatt platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/comwatt/sensor.py", line 32, in async_setup_entry
    new_devices.append(ComwattPowerSensor(hass, entry, child))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/comwatt/sensor.py", line 108, in __init__
    self._attr_unique_id = f"{self._device['id']}_power"
                              ~~~~~~~~~~~~^^^^^^
KeyError: 'id'

**Comment by MateoGreil** [comment]
Hello back,

Can you try with https://github.com/MateoGreil/homeassistant-comwatt/releases/tag/v0.1.8 ? It should be fixed in this version.

**Comment by poowqnp** [comment]
Thank you for that quick fix! Yes it actually seems to work. I'll see if the issue persists. Thanks again!

**Comment by MateoGreil** [comment]
I'll let you create a new issue if other error happen!
Thanks for raising it!
